import { Project } from "@/types/project.types";

export const PROJECTS: Project[] = [
    {
        id: 1,
        title: "AIT University",
        description: "Credit-based online education platform for working professionals.",
        longDescription: "A full-featured online education platform built for working professionals. Supports credit-based learning, course enrollment, progress tracking, and certification. Built with Next.js frontend and Node/Express backend with PostgreSQL.",
        tags: ["Next.js", "Node.js", "PostgreSQL", "Prisma"],
        year: "2024",
        status: "Live",
        gradient: "from-indigo-500/20 to-violet-500/20",
    },
    {
        id: 2,
        title: "PrismV2 ERP",
        description: "Enterprise distribution management system for FMCG industry.",
        longDescription: "A large-scale ERP system for FMCG distribution management. Features 40+ roles, 70+ routes, complex Prisma schema, hierarchical geographic data (Region → Area → Territory → Points), and SKU management.",
        tags: ["Next.js", "Prisma", "TypeScript", "PostgreSQL"],
        year: "2024",
        status: "In Progress",
        gradient: "from-violet-500/20 to-cyan-500/20",
    },
    {
        id: 3,
        title: "Prism Studio",
        description: "Modern creative platform for building digital experiences.",
        longDescription: "A premium SaaS landing platform for Prism Studio showcasing digital product capabilities. Features cinematic hero animations, glassmorphism UI, magnetic buttons, and a fully responsive design system.",
        tags: ["Next.js", "Tailwind CSS", "Framer Motion", "TypeScript"],
        year: "2025",
        status: "In Progress",
        gradient: "from-cyan-500/20 to-indigo-500/20",
    },
    {
        id: 4,
        title: "bKash Payment Gateway",
        description: "Seamless bKash and Nagad payment integration for e-commerce.",
        longDescription: "A reusable payment integration layer supporting bKash and Nagad for Bangladeshi e-commerce platforms. Handles payment initiation, callback verification, refund flows, and webhook management with full TypeScript support.",
        tags: ["Node.js", "Express", "bKash API", "TypeScript"],
        year: "2024",
        status: "Completed",
        gradient: "from-emerald-500/20 to-cyan-500/20",
    },
    {
        id: 5,
        title: "Freelance CRM",
        description: "Client and project management tool for freelancers.",
        longDescription: "A lightweight CRM built for freelancers to manage clients, track project status, send invoices, and monitor earnings. Integrated with Stripe for payment collection and built on Next.js with Prisma ORM.",
        tags: ["Next.js", "Stripe", "Prisma", "PostgreSQL"],
        year: "2025",
        status: "In Progress",
        gradient: "from-indigo-500/20 to-emerald-500/20",
    },
];
